name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  APP_NAME_FRONTEND: ic-fe-2
  APP_NAME_BACKEND: ic-be-2
  GRADLE_USER_HOME: ${{ github.workspace }}/backend/.gradle

jobs:

  #build-deploy-frontend:

   # runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v3
    #- name: Deploying Frontend...
    #  run: docker login -u _ -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com;
     #      docker build --file=frontend/frontend.dockerfile --rm=true -t registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web .;
     #      docker push registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web;
     #      docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} wingrunr21/alpine-heroku-cli:latest container:release web -a ${{ env.APP_NAME_FRONTEND }};
     #      echo "Frontend Deployment Complete!"
           
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Cd
        run : cd ./backend
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
          gradle-version: 6.9
          cache-disabled: true
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
