name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  APP_NAME_FRONTEND: ic-fe-2
  APP_NAME_BACKEND: ic-be-2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploying Frontend...
      run: docker login -u _ -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com
           docker build --file=frontend/frontend.dockerfile --rm=true -t registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web .
           docker push registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web
           docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} wingrunr21/alpine-heroku-cli:latest container:release web -a ${{ env.APP_NAME_FRONTEND }}
           echo "Frontend Deployment Complete!"


